src/Entity/Restaurant.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RestaurantRepository")
 */
class Restaurant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $location;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="restaurants")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $detail;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="restaurant")
     */
    private $images;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $userid;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
    public function __toString()
    {
        return $this->title;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setRestaurant($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getRestaurant() === $this) {
                $image->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getUserid(): ?int
    {
        return $this->userid;
    }

    public function setUserid(?int $userid): self
    {
        $this->userid = $userid;

        return $this;
    }
}

src/Controller/Admin/RestaurantController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Restaurant;
use App\Form\RestaurantType;
use App\Repository\RestaurantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/restaurant")
 */
class RestaurantController extends AbstractController
{
    /**
     * @Route("/", name="admin_restaurant_index", methods={"GET"})
     */
    public function index(RestaurantRepository $restaurantRepository): Response
    {
        $restaurants=$restaurantRepository->getAllRestaurants();
        $slider = $restaurantRepository->findBy(['status'=>'True'],[],10);
        return $this->render('admin/restaurant/index.html.twig', [
            'restaurants' => $restaurants,
            'slider'=>$slider,
        ]);
    }

    /**
     * @Route("/new", name="admin_restaurant_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $restaurant = new Restaurant();
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            //********file upload**>>>>>>>
            /** @var file $file*/
            $file =$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName() .'.'. $file->guessExtension();
               //rastgele bir dosya adı oluşturur g
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e){
                    //h
                }
                $restaurant->setImage($fileName);
            }
            //********file upload**>>>>>>>

            $user=$this->getUser();
            $restaurant->setUserid($user->getId());

            $entityManager->persist($restaurant);
            $entityManager->flush();

            return $this->redirectToRoute('admin_restaurant_index');
        }

        return $this->render('admin/restaurant/new.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_restaurant_show", methods={"GET"})
     */
    public function show(Restaurant $restaurant,RestaurantRepository $restaurantRepository): Response
    {
        $slider = $restaurantRepository->findBy([],[],10);
        return $this->render('admin/restaurant/show.html.twig', [
            'restaurant' => $restaurant,
            'slider'=>$slider,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_restaurant_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Restaurant $restaurant): Response
    {
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var file $file*/
            $file =$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName().'.'. $file->guessExtension();
                //dosya adı+dosyanın uzantısı
                try{
                    $file->move(
                        $this->getParameter('images_directory'), //in servis.yaml
                        $fileName
                    );
                } catch (FileException $e){
                    //h
                }
                $restaurant->setImage($fileName);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_restaurant_index');
        }

        return $this->render('admin/restaurant/edit.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form->createView(),
        ]);
    }
    /**
     * *@return string
     */
    private function generateUniqueFileName(){
        //benzersiz dosya sonra bunu new ve editte çağırdık dosya adı oluşturmak için
        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="admin_restaurant_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Restaurant $restaurant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restaurant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($restaurant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_restaurant_index');
    }
}

src/Controller/RestaurantController.php
<?php

namespace App\Controller;

use App\Entity\Restaurant;
use App\Form\Restaurant1Type;
use App\Repository\RestaurantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user/restaurant")
 */
class RestaurantController extends AbstractController
{
    /**
     * @Route("/", name="user_restaurant_index", methods={"GET"})
     */
    public function index(RestaurantRepository $restaurantRepository): Response
    {   $user=$this->getUser();
        $slider = $restaurantRepository->findBy(['status'=>'True'],[],3);
        return $this->render('restaurant/index.html.twig', [
            'restaurants' => $restaurantRepository->findBy(['userid'=>$user->getId()]),
            'slider'=>$slider,
        ]);
    }

    /**
     * @Route("/new", name="user_restaurant_new", methods={"GET","POST"})
     */
    public function new(Request $request,RestaurantRepository $restaurantRepository): Response
    {
        $restaurant = new Restaurant();
        $form = $this->createForm(Restaurant1Type::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            //********file upload**>>>>>>>
            /** @var file $file*/
            $file =$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName() .'.'. $file->guessExtension();
                //rastgele bir dosya adı oluşturur g
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e){
                    //h
                }
                $restaurant->setImage($fileName);
            }
            //********file upload**>>>>>>>

            $user=$this->getUser();
            $restaurant->setUserid($user->getId());
            $restaurant->setStatus("New");
            $entityManager->persist($restaurant);
            $entityManager->flush();

            return $this->redirectToRoute('user_restaurant_index');
        }
        $slider = $restaurantRepository->findBy(['status'=>'True'],[],3);
        return $this->render('restaurant/new.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form->createView(),
            'slider'=>$slider,
        ]);
    }

    /**
     * @Route("/{id}", name="user_restaurant_show", methods={"GET"})
     */
    public function show(Restaurant $restaurant,RestaurantRepository $restaurantRepository): Response
    {
        $slider = $restaurantRepository->findBy(['status'=>'True'],[],3);
        return $this->render('restaurant/show.html.twig', [
            'restaurant' => $restaurant,
            'slider'=>$slider,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_restaurant_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Restaurant $restaurant,RestaurantRepository $restaurantRepository): Response
    {
        $form = $this->createForm(Restaurant1Type::class, $restaurant);

        $slider = $restaurantRepository->findBy(['status'=>'True'],[],3);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //********file upload**>>>>>>>
            /** @var file $file*/
            $file =$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName() .'.'. $file->guessExtension();
                //rastgele bir dosya adı oluşturur g
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e){
                    //h
                }
                $restaurant->setImage($fileName);
            }
            //********file upload**>>>>>>>
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_restaurant_index');
        }

        return $this->render('restaurant/edit.html.twig', [
            'restaurant' => $restaurant,
            'slider'=>$slider,
            'form' => $form->createView(),
        ]);
    }

    /**
     * *@return string
     */
    private function generateUniqueFileName(){
        //benzersiz dosya sonra bunu new ve editte çağırdık dosya adı oluşturmak için
        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="user_restaurant_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Restaurant $restaurant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restaurant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($restaurant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_restaurant_index');
    }
}

templates/restaurant/_delete_form.html.twig
<form method="post" action="{{ path('user_restaurant_delete', {'id': restaurant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/restaurant/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-info">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/restaurant/edit.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}Comment Edit{% endblock %}

{% block body %}
    <h1>User</h1>

    {{ include('restaurant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_restaurant_index') }}" class="btn btn-info">back to list</a>

{% endblock %}

templates/restaurant/index.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
    <h1>User Restaurant Detail</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Keywords</th>
            <th>Description</th>
            <th>Image</th>
            <th>Address</th>

            <th>City</th>
            <th>Country</th>
            <th>Location</th>
            <th>Status</th>


        </tr>
        </thead>
        <tbody>
        {% for restaurant in restaurants %}
            <tr>
                <td>{{ restaurant.id }}</td>
                <td>{{ restaurant.title }}</td>
                <td>{{ restaurant.keywords }}</td>
                <td>{{ restaurant.description }}</td>
                <td><img src="{{ asset('uploads/images/' ~ restaurant.image) }}" style="height: 30px"> </td>
                <td>{{ restaurant.address }}</td>
                <td>{{ restaurant.city }}</td>
                <td>{{ restaurant.country }}</td>
                <td>
                    <a href="javascript:openWin('{{ path('user_image_new',{'id':restaurant.id} ) }}','','toolbar=no,location=no,directories=0,status=no,top=50,left=100,menuBar=no,scrollBars=yes,resizable=no,width=900,height=600');">
                        <img src="{{ asset('assets/admin/img') }}/gallery.png" style="height: 30px">
                    </a>
                </td>
                <td>{{ restaurant.status }}</td>
                <td>

                    <a href="{{ path('user_restaurant_show', {'id': restaurant.id}) }}" class="btn btn-info">Show</a>
                </td>
                <td>

                    <a href="{{ path('user_restaurant_edit', {'id': restaurant.id}) }}" class="btn btn-info">Edit</a>
                </td>
                <td>
                    {{ include('restaurant/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="15">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_restaurant_new') }}">Create new</a>




{% endblock %}

templates/restaurant/new.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
   <h4>.</h4><h4>.</h4><h4>.</h4>
 <div class="container">

    {{ include('restaurant/_form.html.twig') }}

    <a href="{{ path('user_restaurant_index') }}">back to list</a>

 </div>
    <h4>.</h4><h4>.</h4><h4>.</h4>
{% endblock %}

templates/restaurant/show.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ restaurant.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ restaurant.title }}</td>
            </tr>
            <tr>
                <th>Keywords</th>
                <td>{{ restaurant.keywords }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ restaurant.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ restaurant.image }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ restaurant.address }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ restaurant.phone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ restaurant.email }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ restaurant.city }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ restaurant.country }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ restaurant.location }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ restaurant.status }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ restaurant.createdAt ? restaurant.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ restaurant.updatedAt ? restaurant.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Detail</th>
                <td>{{ restaurant.detail }}</td>
            </tr>
            <tr>
                <th>Userid</th>
                <td>{{ restaurant.userid }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_restaurant_index') }}">back to list</a>

    <a href="{{ path('user_restaurant_edit', {'id': restaurant.id}) }}">edit</a>

    {{ include('restaurant/_delete_form.html.twig') }}
{% endblock %}