src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $crated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(?string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCratedAt(): ?\DateTimeInterface
    {
        return $this->crated_at;
    }

    public function setCratedAt(?\DateTimeInterface $crated_at): self
    {
        $this->crated_at = $crated_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
         //   ->add('roles')
         ->add('roles',ChoiceType::class,[
             'choices'=>[
                 'ADMIN'=>'ROLE_ADMIN',
                 'USER'=>'ROLE_USER'],
         ])


         ->add('password', PasswordType::class, [
             // instead of being set onto the object directly,
             // this is read and encoded in the controller
             'mapped' => false,
             'constraints' => [
                 new NotBlank([
                     'message' => 'Please enter a password',
                 ]),
                 new Length([
                     'min' => 6,
                     'minMessage' => 'Your password should be at least {{ limit }} characters',
                     // max length allowed by Symfony for security reasons
                     'max' => 4096,
                 ]),
             ],
         ])

            ->add('name')
            ->add('surname')

            ->add('image', FileType::class,[
                'label'=> 'Image',
                'mapped'=>false,
                'required' => false,
                'constraints' =>[
                    new File([
                        'maxSize' =>'1024k',
                        'mimeTypes' =>[
                            'image/*', //allimage type
                        ],
                        'mimeTypesMessage' => 'Please upload a valid Image File'
                    ])
                ],
            ])

            ->add('status',ChoiceType::class,[
                'choices'=>[
                    'True'=>'True',
                    'False'=>'False'],
            ])

        ;
        //roles field data transformer

        $builder->get('roles')
            ->addModelTransformer(new CallbackTransformer(
                function ($rolesArray){
                    return count($rolesArray)? $rolesArray[0]: null;
                },
                function ($rolesString){
                    return [$rolesString];
                }
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/admin/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="admin_user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('admin/user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            //********file upload**>>>>>>>
            /** @var file $file*/
            $file =$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName() .'.'. $file->guessExtension();
                //rastgele bir dosya adı oluşturur g
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e){
                    //h
                }
                $user->setImage($fileName);
            }
            //********file upload**>>>>>>>

            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('admin/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user,UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //********file upload**>>>>>>>
            /** @var file $file*/
            $file =$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName() .'.'. $file->guessExtension();
                //rastgele bir dosya adı oluşturur g
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e){
                    //h
                }
                $user->setImage($fileName);
            }
            //********file upload**>>>>>>>

            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * *@return string
     */
    private function generateUniqueFileName(){
        //benzersiz dosya sonra bunu new ve editte çağırdık dosya adı oluşturmak için
        return md5(uniqid());
    }


    /**
     * @Route("/{id}", name="admin_user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_user_index');
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-lg btn-learn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/comments.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}

    <h1>User Comment List</h1>
<div class="container">
<div style="min-height: 700px;">
    <table class="table">
        <thead>
        <tr>

            <th>Subject</th>
            <th>Comment</th>
            <th>Status</th>
            <th>Restaurant</th>
            <th>Created_at</th>

            <th>Rate</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr>

                <td>{{ comment.subject }}</td>
                <td>{{ comment.comment }}</td>
                <td>{{ comment.status }}</td>
                <td nowrap><a href="{{ path('restaurant_show', {'id': comment.restaurantid}) }}">{{ comment.title }}</a></td>
                <td>{{ comment.created_at }}</td>
                <td>{{ comment.rate }}</td>
                <td>
                    <a href="" class="btn btn-danger">Delete</a>
                </td>


            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</div>

{% endblock %}

templates/user/edit.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
    <h4>.</h4>
    <div class="container">
<h1>User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}" class="btn ">back to list</a>

    </div>
    <h4>.</h4><h4>.</h4><h4>.</h4><h4>.</h4>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Image</th>
                <th>Status</th>
                <th>Crated_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.surname }}</td>
                <td>{{ user.image }}</td>
                <td>{{ user.status }}</td>
                <td>{{ user.cratedAt ? user.cratedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/newreservation.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
    <h1 style="color: darkorange;">>Order Form</h1>

    <div class="container" style="max-width:40%;">

    <table class="table" >

        <tr>
            <th>Restaurant  :</th>
            <td>{{ restaurant.title }}</td>
        </tr>
        <tr>
            <th>Food  :</th>
            <td>{{ food.title }}</td>
        </tr>
        <tr>
            <th>Price  :</th>
            <td>{{ food.price }}</td>
        </tr>
        <tr>
            <th>Piece  :</th>
            <td>{{  data.piece  }}</td>
        </tr>
        <tr>
            <th>Total  :</th>
            <td>{{ data.total }}tl</td>
        </tr>
    </table>
    </div>
<div class="container">
    <div class="col-md-12 animate-box fadeInUp animated">




        {{ include('messages.html.twig') }}
        <form name="reservation"  method="post" role="form">
            <div class="col-md-12">
                <div class="form-group">
                    <input style="background-color: #d0e9c6;" type="text" class="form-control" id="reservation_name" name="reservation[name]" value="{{ app.user.name }}" placeholder="Name" data-msg="Please enter at least 4 character">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <input style="background-color: #d0e9c6;" type="text" class="form-control" id="reservation_surname" name="reservation[surname]" value="{{ app.user.surname }}" placeholder="Surname" data-msg="Please enter at least 4 character">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <input style="background-color: #d0e9c6;" type="text" class="form-control" id="reservation_email" name="reservation[email]" value="{{ app.user.email }}" placeholder="Email">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <input style="background-color: #d0e9c6;"  type="text" class="form-control" id="reservation_phone" name="reservation[phone]" maxlength="75" placeholder="Phone">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">

                    <textarea style="background-color: #d0e9c6;"  name="message" data-rule="required" class="form-control" id="reservation_message" name="reservation[message]" maxlength="255" cols="30" rows="7" placeholder="Message"></textarea>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <input type="hidden"  name="piece" value="{{ data.piece }}">
                    ******CREDIT CARD INFORMATION****** <br>
                    <input type="hidden"  name="token" value="{{ csrf_token('form-reservation') }}" />
                    <input  type="submit" value="Order" class="btn btn-primary" style="min-width: 40%;">
                </div>
            </div>
        </form>
    </div>
    </div>
    </div>


{% endblock %}

templates/user/reservation_show.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
<h1>Reservations</h1>



<table class="table">


    <tr>

        <th>Restaurant</th><td>
            <a href="{{ path('restaurant_show', {'id': reservation[0].restaurantid}) }}">
                {{ reservation[0].rname }}
            </a>
        </td>
    </tr>
    <tr>
        <th>Food</th><td>{{ reservation[0].fname }}</td>
    </tr>
    <tr>
        <th>Name</th><td>{{ reservation[0].name }}</td>
    </tr>
    <tr>
        <th>Surname</th><td>{{ reservation[0].surname }}</td>
    </tr>
    <tr>
        <th>Email</th><td>{{ reservation[0].email }}</td>
    </tr>
    <tr>
        <th>Phone</th><td>{{ reservation[0].phone }}</td>
    </tr>
    <tr>
        <th>Total</th><td>{{ reservation[0].total }}</td>
    </tr>
    <tr>
        <th>Note</th><td>{{ reservation[0].note }}</td>
    </tr>
    <tr>
        <th>Message</th><td>{{ reservation[0].message }}</td>
    </tr>
    <tr>
        <th>Status</th><td>{{ reservation[0].status }}</td>
    </tr>
    <tr>
        <th>Created_at</th><td>{{ reservation[0].created_at }}</td>
    </tr>
    <tr>
        <th>Updated_at</th><td>{{ reservation[0].updated_at }}</td>
    </tr>

    </tbody>
</table>

{% endblock %}

templates/user/reservations.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
<h1>Reservations</h1>

<div class="container">

    <table class="table">
        <thead>
        <tr>
            <th>Restaurant</th>
            <th>Food</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Email</th>
            <th>Phone</th>

            <th>Total</th>
            <th>Note</th>
            <th>Message</th>
            <th>Status</th>
            <th>Created_at</th>
            <th>Updated_at</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>

                <td>
                    <a href="{{ path('restaurant_show', {'id': reservation.restaurantid}) }}">
                    {{ reservation.rname }}
                    </a>
                </td>
                <td>{{ reservation.fname }}</td>
                <td>{{ reservation.name }}</td>
                <td>{{ reservation.surname }}</td>
                <td>{{ reservation.email }}</td>
                <td>{{ reservation.phone }}</td>
                <td>{{ reservation.total }}</td>
                <td>{{ reservation.note }}</td>
                <td>{{ reservation.message }}</td>
                <td>{{ reservation.status }}</td>
                <td>{{ reservation.created_at }}</td>
                <td>{{ reservation.updated_at }}</td>
                <td>
                    <a class="btn btn-success" href="{{ path('user_reservation_show', {'id': reservation.id}) }}">Show</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="19">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
    <h4>.</h4><h4>.</h4><h4>.</h4><h4>.</h4>

{% endblock %}

templates/user/restaurants.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
    <h1>My Restaurent List</h1>





{% endblock %}

templates/user/show.html.twig
{% extends 'menubase.html.twig' %}

{% block title %}{{ app.user.name }} Profile{% endblock %}

{% block body %}
    <h6>.</h6>
    <h1>User</h1>
<div class="container " >
    <table class="table" >
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ app.user.id }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ app.user.email }}</td>
        </tr>
        <tr>
            <th>Roles</th>
            <td>{{ app.user.roles ? app.user.roles|json_encode : '' }}</td>
        </tr>
        <tr>
            <th>Password</th>
            <td>{{ app.user.password }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ app.user.name }}</td>
        </tr>
        <tr>
            <th>Surname</th>
            <td>{{ app.user.surname }}</td>
        </tr>
        <tr>
            <th>Image</th>
            <td>{{ app.user.image }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{{ app.user.status }}</td>
        </tr>
        <tr>
            <th>Crated_at</th>
            <td>{{ app.user.cratedAt ? app.user.cratedAt|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Updated_at</th>
            <td>{{ app.user.updatedAt ? app.user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
        </tbody>
    </table>




    <a href="{{ path('user_edit', {'id': app.user.id}) }}" class="btn btn-primary btn-lg btn-learn">Edit Profile</a>
</div>
    <h4>.</h4><h4>.</h4><h4>.</h4><h4>.</h4>


{% endblock %}

templates/user/usermenu.html.twig
<nav id="colorlib-main-nav" role="navigation">
    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
<div class="js-fullheight colorlib-table" style="height: 608px;">
    <div class="colorlib-table-cell js-fullheight" style="height: 608px;">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="form-group">
                    <input type="text" class="form-control" id="search" placeholder="Enter any key to search...">
                    <button type="submit" class="btn btn-primary"><i class="icon-search3"></i></button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <ul>
                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <li>
                        <a href="/user"><img src="{{asset('uploads/images/' ~ app.user.image) }}"  style="height: 30px">{{ app.user.name }}{{ app.user.surname }}</a>
                        {{ app.user.name }}{{ app.user.surname }}
                    </li>

                    {% endif %}

                    <li><a href="/">Home</a></li>
                    <li><a href="/user">My Profile</a></li>
                    <li><a href="/user/reservations">My Order</a></li>
                    <li><a href="/user/restaurant">My Restaurants</a></li>
                    <li ><a href="/user/comments" >My Comments</a></li>
                    <li><a href="/logout">Logout</a></li>

                </ul>
            </div>
        </div>
    </div>
</div>
</nav>

<div id="colorlib-page"><header>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="colorlib-navbar-brand">
                        <a class="colorlib-logo" href="index.html"><i class="flaticon-cutlery"></i><span>Lu</span><span>to</span></a>
                    </div>
                    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
                </div>
            </div>
        </div>
    </header>